# Generated by Django 3.0.8 on 2020-07-27 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitch_channel', models.CharField(blank=True, db_index=True, default=None, max_length=128, null=True, unique=True)),
                ('youtube_url', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('youtube_time', models.FloatField(blank=True, default=None, null=True)),
                ('irl_time', models.FloatField(blank=True, default=None, null=True)),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
