# Generated by Django 3.0.8 on 2020-07-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caster',
            name='url_path',
            field=models.CharField(db_index=True, default=None, max_length=128, null=True, unique=True),
        ),
    ]
